[project]
name = "mist"
version = "0.1.0"
description = "A Python Command Line Interface (CLI) application and package to run the Merging Instance Segmentation Tiler (MIST) with ML computer vision models"
authors = [
    {name = "Christopher Field", email = "chris.field@theiascientific.com"},
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Environment :: GPU",
    "Framework :: Pydantic",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Recognition",
]
dependencies = [
    "imagecodecs",
    "natsort",
    "opencv-python-headless",
    "pydantic",
    "supervision>=0.30",
    "tifffile",
]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "black",
    "build",
    "flake8",
    "hatch",
    "isort",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "twine"
]
cli = ["typer", "ultralytics-opencv-headless"]

[project.scripts]
mist = "mist.cli:app"

[project.urls]
Homepage = "https://github.com/Theia-Scientific/mist"
Source = "https://github.com/Theia-Scientific/mist"
Tracker = "https://github.com/Theia-Scientific/mist/issues"

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
    "@abstractmethod",
    "@abc.abstractmethod"
]
omit = [ "__main__.py" ]
